### ISSUE TITLE
Cat-merge: when skipping edgefiles, corresponding nodefiles still get added

### ISSUE THREAD

**Issue by caufieldjh** [ncbo/kg-bioportal#17]
This error breaks a merge:
```
15:28:50  Traceback (most recent call last):
15:28:50    File "run.py", line 136, in <module>
15:28:50      cli()
15:28:50    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
15:28:50      return self.main(*args, **kwargs)
15:28:50    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
15:28:50      rv = self.invoke(ctx)
15:28:50    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
15:28:50      return _process_result(sub_ctx.command.invoke(sub_ctx))
15:28:50    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
15:28:50      return ctx.invoke(self.callback, **ctx.params)
15:28:50    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
15:28:50      return __callback(*args, **kwargs)
15:28:50    File "run.py", line 132, in catmerge
15:28:50      merge_with_cat_merge(merge_all, include_only, exclude)
15:28:50    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/kg_bioportal/merge_utils/merge_kg.py", line 143, in merge_with_cat_merge
15:28:50      cat_merge_merge(
15:28:50    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/cat_merge/merge.py", line 17, in merge
15:28:50      edge_dfs = read_dfs(edges)
15:28:50    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/cat_merge/file_utils.py", line 23, in read_dfs
15:28:50      df = pd.read_csv(file, sep="\t", dtype="string", lineterminator="\n", index_col='id', quoting=csv.QUOTE_NONE)
15:28:50    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
15:28:50      return func(*args, **kwargs)
15:28:50    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
15:28:50      return _read(filepath_or_buffer, kwds)
15:28:50    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 581, in _read
15:28:50      return parser.read(nrows)
15:28:50    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1254, in read
15:28:50      index, columns, col_dict = self._engine.read(nrows)
15:28:50    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 271, in read
15:28:50      values = data.pop(self.index_col[i])
15:28:50  KeyError: 'id'
```

Solution is building on https://github.com/ncbo/kg-bioportal/pull/15 to ignore:
* all empty files
* those without 'id' field
* nodefiles matching ignored edgefiles, and vice-versa

**Comment by caufieldjh** [comment]
The lack of an 'id' field probably suggests a larger issue with the source transform, so that should be handled before parsing with kg-bioportal

**Comment by caufieldjh** [comment]
See #18

**Comment by caufieldjh** [comment]
Reopening as this is still happening, though several transforms are certainly being ignored as intended:
```
12:09:04  Ignoring ../BioPortal-to-KGX/transformed/ontologies/VODANA-UG/VODANA-UG_1_edges.tsv as it contains no edges or edge ids. Will also ignore ../BioPortal-to-KGX/transformed/ontologies/VODANA-UG/VODANA-UG_1_nodes.tsv.
12:09:04  Ignoring ../BioPortal-to-KGX/transformed/ontologies/VODANA-UG/VODANA-UG_1_nodes.tsv as it contains no nodes or node ids. Will also ignore ../BioPortal-to-KGX/transformed/ontologies/VODANA-UG/VODANA-UG_1_edges.tsv.
12:09:04  Ignoring ../BioPortal-to-KGX/transformed/ontologies/HMIS033B/HMIS033B_1_edges.tsv as it contains no edges or edge ids. Will also ignore ../BioPortal-to-KGX/transformed/ontologies/HMIS033B/HMIS033B_1_nodes.tsv.
12:09:04  Ignoring ../BioPortal-to-KGX/transformed/ontologies/HMIS033B/HMIS033B_1_nodes.tsv as it contains no nodes or node ids. Will also ignore ../BioPortal-to-KGX/transformed/ontologies/HMIS033B/HMIS033B_1_edges.tsv.
12:09:04  Ignoring ../BioPortal-to-KGX/transformed/ontologies/EHDAA/EHDAA_7_edges.tsv as it contains no edges or edge ids. Will also ignore ../BioPortal-to-KGX/transformed/ontologies/EHDAA/EHDAA_7_nodes.tsv.
12:09:04  Ignoring ../BioPortal-to-KGX/transformed/ontologies/ROCKNROLLTEST/ROCKNROLLTEST_2_edges.tsv as it contains no edges or edge ids. Will also ignore ../BioPortal-to-KGX/transformed/ontologies/ROCKNROLLTEST/ROCKNROLLTEST_2_nodes.tsv.
12:09:04  Ignoring ../BioPortal-to-KGX/transformed/ontologies/ROCKNROLLTEST/ROCKNROLLTEST_2_nodes.tsv as it contains no nodes or node ids. Will also ignore ../BioPortal-to-KGX/transformed/ontologies/ROCKNROLLTEST/ROCKNROLLTEST_2_edges.tsv.
```

**Comment by caufieldjh** [comment]
One possibility is that at least one node or edge is missing an id but its file still contains an `id` column.

**Comment by caufieldjh** [comment]
Something about the `IDODEN` ontology makes `pandas` very angry - it claims there is an extra EOF on line 4371 in the node or edgefile

**Comment by caufieldjh** [comment]
See #20 - all transforms not parsed by `pandas` are ignored for the merge.
