### ISSUE TITLE
Pandas parsing error halts merge

### ISSUE THREAD

**Issue by caufieldjh** [ncbo/kg-bioportal#21]
The `IDODEN` ontology really doesn't work well with `pandas`. Here's what it does during validation:
```
13:44:11  Validating IDODEN...
13:44:11  Traceback (most recent call last):
13:44:11    File "run.py", line 136, in <module>
13:44:11      cli()
13:44:11    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
13:44:11      return self.main(*args, **kwargs)
13:44:11    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
13:44:11      rv = self.invoke(ctx)
13:44:11    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
13:44:11      return _process_result(sub_ctx.command.invoke(sub_ctx))
13:44:11    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
13:44:11      return ctx.invoke(self.callback, **ctx.params)
13:44:11    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
13:44:11      return __callback(*args, **kwargs)
13:44:11    File "run.py", line 132, in catmerge
13:44:11      merge_with_cat_merge(merge_all, include_only, exclude)
13:44:11    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/kg_bioportal/merge_utils/merge_kg.py", line 135, in merge_with_cat_merge
13:44:11      nodedf = pd.read_csv(path, sep='\t', index_col='id')
13:44:11    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
13:44:11      return func(*args, **kwargs)
13:44:11    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
13:44:11      return _read(filepath_or_buffer, kwds)
13:44:11    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 581, in _read
13:44:11      return parser.read(nrows)
13:44:11    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1254, in read
13:44:11      index, columns, col_dict = self._engine.read(nrows)
13:44:11    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal@2/gitrepo/venv/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 225, in read
13:44:11      chunks = self._reader.read_low_memory(nrows)
13:44:11    File "pandas/_libs/parsers.pyx", line 805, in pandas._libs.parsers.TextReader.read_low_memory
13:44:11    File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._read_rows
13:44:11    File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
13:44:11    File "pandas/_libs/parsers.pyx", line 1960, in pandas._libs.parsers.raise_parser_error
13:44:11  pandas.errors.ParserError: Error tokenizing data. C error: EOF inside string starting at row 4371
```

See if it can be repaired. I have yet to find the offending EOF in the specified row.

**Comment by caufieldjh** [comment]
For now, just catch the exception.
