### ISSUE TITLE
Build fails: KeyError: 'in_taxon'

### ISSUE THREAD

**Issue by caufieldjh** [ncbo/kg-bioportal#25]
The most recent build fails during merge as follows:
```
20:51:31  Reading node and edge files
20:51:31  Merging...
20:51:31  Generating QC report
20:51:31  Traceback (most recent call last):
20:51:31    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
20:51:31      return self._engine.get_loc(casted_key)
20:51:31    File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
20:51:31    File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
20:51:31    File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
20:51:31    File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
20:51:31  KeyError: 'in_taxon'
20:51:31  
20:51:31  The above exception was the direct cause of the following exception:
20:51:31  
20:51:31  Traceback (most recent call last):
20:51:31    File "run.py", line 136, in <module>
20:51:31      cli()
20:51:31    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
20:51:31      return self.main(*args, **kwargs)
20:51:31    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
20:51:31      rv = self.invoke(ctx)
20:51:31    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
20:51:31      return _process_result(sub_ctx.command.invoke(sub_ctx))
20:51:31    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
20:51:31      return ctx.invoke(self.callback, **ctx.params)
20:51:31    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
20:51:31      return __callback(*args, **kwargs)
20:51:31    File "run.py", line 132, in catmerge
20:51:31      merge_with_cat_merge(merge_all, include_only, exclude)
20:51:31    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/kg_bioportal/merge_utils/merge_kg.py", line 165, in merge_with_cat_merge
20:51:31      cat_merge_merge(
20:51:31    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/venv/lib/python3.8/site-packages/cat_merge/merge.py", line 59, in merge
20:51:31      qc_report = create_qc_report(kg)
20:51:31    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/venv/lib/python3.8/site-packages/cat_merge/qc_utils.py", line 88, in create_qc_report
20:51:31      nodes['in_taxon'] = nodes['in_taxon'].fillna('missing taxon')
20:51:31    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
20:51:31      indexer = self.columns.get_loc(key)
20:51:31    File "/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
20:51:31      raise KeyError(key) from err
20:51:31  KeyError: 'in_taxon'
```

**Comment by caufieldjh** [comment]
I believe this happens because the cat-merge [qc utils](https://github.com/monarch-initiative/cat-merge/blob/main/cat_merge/qc_utils.py) try to use the `in_taxon` field as a way to enumerate taxons specified among nodes, but the inputs for kg-bioportal do not use this field.

**Comment by caufieldjh** [comment]
Temporary solution is to pin cat-merge to 0.1.7

**Comment by caufieldjh** [comment]
Fixed in cat-merge.
