### ISSUE TITLE
`GAZ` does not transform

### ISSUE THREAD

**Issue by caufieldjh** [ncbo/kg-bioportal#84]
GAZ is provided as a ZIP, and ROBOT doesn't know what to do with that, so it doesn't transform.

Full stack trace from Jenkins build:
```
11:21:00  Converting data/raw/GAZ/14/gaz-fixed.zip to data/transformed/GAZ/14/GAZ.owl...
11:21:00  ROBOT encountered an error: 
11:21:00  
11:21:00    RAN: /var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/robot convert --input data/raw/GAZ/14/gaz-fixed.zip --output data/transformed/GAZ/14/GAZ.owl -vvv
11:21:00  
11:21:00    STDOUT:
11:21:00  2024-09-06 18:20:58,323 DEBUG org.obolibrary.robot.IOHelper - Loading ontology data/raw/GAZ/14/gaz-fixed.zip with catalog file null
11:21:00  2024-09-06 18:20:58,328 DEBUG org.semanticweb.owlapi.utilities.Injector - Loading file META-INF/services/org.semanticweb.owlapi.model.OWLOntologyManager
11:21:00  2024-09-06 18:20:58,328 DEBUG org.semanticweb.owlapi.utilities.Injector - Loading URL for service jar:file:/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/robot.jar!/META-INF/services/org.semanticweb.owlapi.model.OWLOntologyManager
11:21:00  2024-09-06 18:20:58,329 DEBUG org.semanticweb.owlapi.utilities.Injector - Loading URL for service jar:file:/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/robot.jar!/META-INF/services/org.semanticweb.owlapi.model.OWLOntolog... (10891 more, please see e.stdout)
11:21:00  
11:21:00    STDERR:
11:21:00  java.lang.IllegalArgumentException: java.io.IOException: errors#INVALID ONTOLOGY FILE ERROR Could not load a valid ontology from file: gaz-fixed.zip
11:21:00  	at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:585)
11:21:00  	at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:539)
11:21:00  	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:130)
11:21:00  	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:244)
11:21:00  	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:188)
11:21:00  	at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
11:21:00  	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:65)
11:21:00  Caused by: java.io.IOException: errors#INV... (44860 more, please see e.stderr)
11:21:00  Relaxing data/transformed/GAZ/14/GAZ.owl to data/transformed/GAZ/14/GAZ_relaxed.owl...
11:21:00  ROBOT encountered an error: 
11:21:00  
11:21:00    RAN: /var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/robot relax --input data/transformed/GAZ/14/GAZ.owl --output data/transformed/GAZ/14/GAZ_relaxed.owl -vvv
11:21:00  
11:21:00    STDOUT:
11:21:00  2024-09-06 18:20:59,773 DEBUG org.obolibrary.robot.IOHelper - Loading ontology data/transformed/GAZ/14/GAZ.owl with catalog file null
11:21:00  2024-09-06 18:20:59,778 DEBUG org.semanticweb.owlapi.utilities.Injector - Loading file META-INF/services/org.semanticweb.owlapi.model.OWLOntologyManager
11:21:00  2024-09-06 18:20:59,779 DEBUG org.semanticweb.owlapi.utilities.Injector - Loading URL for service jar:file:/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/robot.jar!/META-INF/services/org.semanticweb.owlapi.model.OWLOntologyManager
11:21:00  2024-09-06 18:20:59,779 DEBUG org.semanticweb.owlapi.utilities.Injector - Loading URL for service jar:file:/var/lib/jenkins/workspace/NCBO/kg-bioportal/gitrepo/robot.jar!/META-INF/services/org.semanticweb.owlapi.model.OWLOntol... (7934 more, please see e.stdout)
11:21:00  
11:21:00    STDERR:
11:21:00  java.lang.IllegalArgumentException: org.semanticweb.owlapi.io.OWLOntologyInputSourceException: java.io.FileNotFoundException: data/transformed/GAZ/14/GAZ.owl (No such file or directory)
11:21:00  	at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:585)
11:21:00  	at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:539)
11:21:00  	at org.obolibrary.robot.RelaxCommand.execute(RelaxCommand.java:114)
11:21:00  	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:244)
11:21:00  	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:188)
11:21:00  	at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
11:21:00  	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:65)
11:21:00  Caused by... (1745 more, please see e.stderr)
11:21:00  [KGX][owl_source.py][               parse] INFO: Parsing data/transformed/GAZ/14/GAZ_relaxed.owl with 'xml' format
11:21:00  ERROR:root:Error transforming GAZ to KGX nodes and edges: [Errno 2] No such file or directory: '/var/lib/jenkins/workspace/NCBO/kg-bioportal/data/transformed/GAZ/14/GAZ_relaxed.owl'
11:21:00  ERROR:root:Error transforming data/raw/GAZ/14/gaz-fixed.zip.
```

**Comment by caufieldjh** [comment]
Stale - covered by #118 now, but the issue with ROBOT not handling ZIP decompression is still good to remember.
